### ISSUE TITLE
wrong result

### ISSUE THREAD

**Issue by ppjxhyyy** [miloyip/dtoa-benchmark#20]
hi, `dtoa_milo` returns wrong result when value = 16385.0.

Many data have returned wrong results

**Comment by ppjxhyyy** [comment]
vs2013 x64

**Comment by ppjxhyyy** [comment]
I find the error.

`if (dk - k > DBL_MAX)`   x

`if(dk - k > 0)`  √

**Comment by miloyip** [comment]
Thank you
